name: Splatoon3 Battlelog Uplorder

on:
  schedule:
    - cron: '0 0-23/2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACC_LOC: ${{ secrets.ACC_LOC }}
      GTOKEN: ${{ secrets.GTOKEN }}
      BULLETTOKEN: ${{ secrets.BULLETTOKEN }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      F_GEN: ${{ secrets.F_GEN }}

    name: Splatoon3 Battlelog Uploader
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Checkout frozenpandaman/s3s
        uses: actions/checkout@v3
        with:
          repository: 'frozenpandaman/s3s'
          path: s3s

      - name: Generate config.txt
        working-directory: s3s
        run: |
          echo '"api_key": "IIQYBqd-04ClqbR3DfLnSolHAlKL-TcZS7aV8eixCJs", "acc_loc": "ja-JP|JP", "gtoken": "eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8vYXBpLWxwMS56bmMuc3J2Lm5pbnRlbmRvLm5ldC92MS9XZWJTZXJ2aWNlL0NlcnRpZmljYXRlL0xpc3QiLCJraWQiOiJCeFVMYU9NYlMzc2dDaWNLVk81LXNyNWRVWEUiLCJ0eXAiOiJKV1QifQ.eyJpc0NoaWxkUmVzdHJpY3RlZCI6ZmFsc2UsImF1ZCI6IjY2MzM2NzcyOTE1NTI3NjgiLCJleHAiOjE3MTk2NTc3MDIsImlhdCI6MTcxOTY0NjkwMiwiaXNzIjoiYXBpLWxwMS56bmMuc3J2Lm5pbnRlbmRvLm5ldCIsImp0aSI6ImQ0ZTJmZDdlLTU0ZmItNDY0OC05MjFhLTQzZDYzMzI0ODhkNyIsInN1YiI6NDU4MzIzNzc0NTkzNDMzNiwibGlua3MiOnsibmV0d29ya1NlcnZpY2VBY2NvdW50Ijp7ImlkIjoiNmYxY2VmMDIwN2U2OTg0MCJ9fSwidHlwIjoiaWRfdG9rZW4iLCJtZW1iZXJzaGlwIjp7ImFjdGl2ZSI6dHJ1ZX19.hRLO2otersU_CunybfuLEPZFd_Tem9UE91Yo04FTM11FAgzZKDAcSZ60YCQScv7PLxRa2wPC8QPqm4-M2mK0ZpAIJUob-jDmUodPNlNvBchHhnMgsjMFQKrmic2VVnoMpEg20SzxfTq9PzGl-xwkG50cxnPZWN3rv6HP1QrYJ1xdpchepN5jJSyhWw9vHpKc9FeyZxNMhwZpE4pxLgzdZSn6nBNn_n5hc7Azitl2-YM2psngjQsu5mueqtm883wSWxDlBAqPZD5ILhtq6gwlII4U1JfVK7_dnbyoEOuNaI5Gn5_vqeazUhyz_L8fv4CZsfaLHyUAGBa9JKnm1SMQ1w", "bullettoken": "P0HORWDsSCGKbPAwyyl7YVCyasfg2dqR4Zobd0Et1t293t6zID--JNbc07hsPK3FVW01wfJM6Itx9nGB-xbX9rnLmIeaXTNPk32NaVraA2Z82pIyQSZBTZ1wDJ4=", "session_token": "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3MWI5NjNjMWI3YjZkMTE5IiwiaWF0IjoxNzE3MjQxMjgyLCJzdWIiOiJjZTBjZjBhNzFmMzhmNDg5IiwianRpIjoxNTE4MTc5MjUxMiwic3Q6c2NwIjpbMCw4LDksMTcsMjNdLCJ0eXAiOiJzZXNzaW9uX3Rva2VuIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5uaW50ZW5kby5jb20iLCJleHAiOjE3ODAzMTMyODJ9.RpyjC5La08_YuyHyGefYTVkSFVwW5Q0yiX00p_gLcZ8", "f_gen": "https://api.imink.app/f"' > config.txt
          cat config.txt
          
      - name: Install s3s requirements
        working-directory: s3s
        run: |
          pip install -r requirements.txt
          
      - name: Run s3s
        working-directory: s3s
        run: |
          python3 s3s.py -nsr -r
